web/router.ex
defmodule WebgeeksRaffle.Router do
  use WebgeeksRaffle.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", WebgeeksRaffle do
    pipe_through :browser

    get "/", PageController, :index
    get "/submissions/new", SubmissionController, :new
    post "/submissions", SubmissionController, :create
  end

  scope "/", WebgeeksRaffle do
    pipe_through :protected

    get "submissions/draw_winner", SubmissionController, :draw_winner
    get "/submissions", SubmissionController, :index
    get "/submissions/:id/edit", SubmissionController, :edit
    get "/submissions/:id", SubmissionController, :show
    patch "/submissions/:id", SubmissionController, :update
    put "/submissions/:id", SubmissionController, :update
    delete "/submissions/:id", SubmissionController, :delete

    resources "/double_submissions", DoubleSubmissionController
  end
end

web/models/double_submission.ex
defmodule WebgeeksRaffle.DoubleSubmission do
  use WebgeeksRaffle.Web, :model

  schema "double_submissions" do
    field :first_name, :string
    field :last_name, :string
    field :job_title, :string
    field :twitter_handle, :string
    field :email, :string
    field :winner, :boolean

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:first_name, :last_name, :job_title, :twitter_handle, :email, :winner])
    |> unique_constraint(:twitter_handle)
    |> unique_constraint(:email)
    |> validate_required([:first_name, :last_name, :job_title, :twitter_handle])
    |> validate_format(:email, ~r/@/)
  end
end

web/controllers/double_submission_controller.ex
defmodule WebgeeksRaffle.DoubleSubmissionController do
  use WebgeeksRaffle.Web, :controller

  alias WebgeeksRaffle.DoubleSubmission

  def index(conn, _params) do
    double_submissions = Repo.all(DoubleSubmission)
    render(conn, "index.html", double_submissions: double_submissions)
  end

  def new(conn, _params) do
    changeset = DoubleSubmission.changeset(%DoubleSubmission{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"double_submission" => double_submission_params}) do
    changeset = DoubleSubmission.changeset(%DoubleSubmission{}, double_submission_params)

    case Repo.insert(changeset) do
      {:ok, _submission} ->
        conn
        |> put_flash(:info, "DoubleSubmission created successfully.")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, errors: changeset.errors)
    end
  end

  def show(conn, %{"id" => id}) do
    double_submission = Repo.get!(DoubleSubmission, id)
    render(conn, "show.html", double_submission: double_submission)
  end

  def edit(conn, %{"id" => id}) do
    double_submission = Repo.get!(DoubleSubmission, id)
    changeset = DoubleSubmission.changeset(double_submission)
    render(conn, "edit.html", double_submission: double_submission, changeset: changeset)
  end

  def update(conn, %{"id" => id, "double_submission" => double_submission_params}) do
    double_submission = Repo.get!(DoubleSubmission, id)
    changeset = DoubleSubmission.changeset(double_submission, double_submission_params)
    case Repo.update(changeset) do
      {:ok, double_submission} ->
        conn
        |> put_flash(:info, "DoubleSubmission updated successfully.")
        |> redirect(to: double_submission_path(conn, :show, double_submission))
      {:error, changeset} ->
        render(conn, "edit.html", double_submission: double_submission, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    double_submission = Repo.get!(DoubleSubmission, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(double_submission)

    conn
    |> put_flash(:info, "DoubleSubmission deleted successfully.")
    |> redirect(to: double_submission_path(conn, :index))
  end
end

web/views/double_submission_view.ex
defmodule WebgeeksRaffle.DoubleSubmissionView do
  use WebgeeksRaffle.Web, :view
end

web/templates/double_submission/edit.html.eex
<h2>Edit double submission</h2>

<%= render "form.html", changeset: @changeset,
                        action: double_submission_path(@conn, :update, @double_submission) %>

web/templates/double_submission/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= text_input f, :first_name, class: "form-control", placeholder: "First name" %>
          <%= error_tag f, :first_name %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          <%= text_input f, :last_name, class: "form-control", placeholder: "Last name" %>
          <%= error_tag f, :last_name %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= text_input f, :job_title, class: "form-control", placeholder: "Job title" %>
      <%= error_tag f, :job_title %>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <%= text_input f, :twitter_handle, class: "form-control", placeholder: "Twitter" %>
          </div>
          <%= error_tag f, :twitter_handle %>
        </div>
        <div class="col-lg-6">
          <%= text_input f, :email, class: "form-control", placeholder: "Email adress" %>
          <%= error_tag f, :email %>
        </div>
    </div>
  </div>

  <div class="form-group">
    <%= checkbox f, :winner %>
    <%= label f, "Winner?" %>
    <%= error_tag f, :winner %>
  </div>

  <div class="col-lg-12">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/double_submission/index.html.eex
<div class="row">
  <div class="form-group">
    <%= link "New double submission", to: double_submission_path(@conn, :new), class: "btn btn-primary" %>
    <%= link "Regular submissions", to: submission_path(@conn, :index), class: "btn btn-primary" %>
  </div>
</div>

<h2>Secondary Door Prize Entries</h2>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Job title</th>
      <th>Twitter handle</th>
      <th>Email</th>
      <th>Winner</th>

      <th>Actions</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for double_submission <- @double_submissions do %>
    <tr>
      <td><%= double_submission.first_name %></td>
      <td><%= double_submission.last_name %></td>
      <td><%= double_submission.job_title %></td>
      <td><%= double_submission.twitter_handle %></td>
      <td><%= double_submission.email %></td>
      <td><%= double_submission.winner %></td>

      <td class="text-right">
        <%= link "Edit", to: double_submission_path(@conn, :edit, double_submission), class: "btn btn-default btn-xs" %>
      </td>
      <td>
        <%= link "Delete", to: double_submission_path(@conn, :delete, double_submission), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/double_submission/new.html.eex
<h2>New double submission</h2>

<%= render "form.html", changeset: @changeset,
                        action: double_submission_path(@conn, :create) %>

web/templates/double_submission/show.html.eex
<h2>Double Submission for <%= "#{@double_submission.first_name} #{@double_submission.last_name}" %></h2>

<ul>

  <li>
    <strong>First name:</strong>
    <%= @double_submission.first_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @double_submission.last_name %>
  </li>

  <li>
    <strong>Job title:</strong>
    <%= @double_submission.job_title %>
  </li>

  <li>
    <strong>Twitter handle:</strong>
    <%= @double_submission.twitter_handle %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @double_submission.email %>
  </li>

</ul>
<div class="col-lg-12">
  <div class="row">
    <div class="form-group">
      <%= link "Edit", to: double_submission_path(@conn, :edit, @double_submission), class: "btn btn-primary" %>
      <%= link "View All", to: double_submission_path(@conn, :index), class: "btn btn-primary" %>
    </div>
  </div>
</div>