web/router.ex
defmodule WebgeeksRaffle.Router do
  use WebgeeksRaffle.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", WebgeeksRaffle do
    pipe_through :browser

    get "/", PageController, :index
    get "/submissions/new", SubmissionController, :new
    post "/submissions", SubmissionController, :create
  end

  scope "/", WebgeeksRaffle do
    pipe_through :protected

    get "submissions/draw_winner", SubmissionController, :draw_winner
    get "/submissions", SubmissionController, :index
    get "/submissions/:id/edit", SubmissionController, :edit
    get "/submissions/:id", SubmissionController, :show
    patch "/submissions/:id", SubmissionController, :update
    put "/submissions/:id", SubmissionController, :update
    delete "/submissions/:id", SubmissionController, :delete

    resources "/double_submissions", DoubleSubmissionController
  end
end

web/models/submission.ex
defmodule WebgeeksRaffle.Submission do
  use WebgeeksRaffle.Web, :model

  schema "submissions" do
    field :first_name, :string
    field :last_name, :string
    field :job_title, :string
    field :twitter_handle, :string
    field :email, :string
    field :winner, :boolean

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:first_name, :last_name, :job_title, :twitter_handle, :email, :winner])
    |> unique_constraint(:twitter_handle)
    |> unique_constraint(:email)
    |> validate_required([:first_name, :last_name, :job_title, :twitter_handle])
    |> validate_format(:email, ~r/@/)
  end
end

web/controllers/submission_controller.ex
defmodule WebgeeksRaffle.SubmissionController do
  use WebgeeksRaffle.Web, :controller

  alias WebgeeksRaffle.Submission
  alias WebgeeksRaffle.DoubleSubmission

  def index(conn, _params) do
    submissions = Repo.all(Submission)
    render(conn, "index.html", submissions: submissions)
  end

  def new(conn, _params) do
    changeset = Submission.changeset(%Submission{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"submission" => submission_params}) do
    changeset = Submission.changeset(%Submission{}, submission_params)

    case Repo.insert(changeset) do
      {:ok, _submission} ->
        conn
        |> put_flash(:info, "Submission created successfully.")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, errors: changeset.errors)
    end
  end

  def show(conn, %{"id" => id}) do
    submission = Repo.get!(Submission, id)
    render(conn, "show.html", submission: submission)
  end

  def edit(conn, %{"id" => id}) do
    submission = Repo.get!(Submission, id)
    changeset = Submission.changeset(submission)
    render(conn, "edit.html", submission: submission, changeset: changeset)
  end

  def update(conn, %{"id" => id, "submission" => submission_params}) do
    submission = Repo.get!(Submission, id)
    changeset = Submission.changeset(submission, submission_params)
    case Repo.update(changeset) do
      {:ok, submission} ->
        conn
        |> put_flash(:info, "Submission updated successfully.")
        |> redirect(to: submission_path(conn, :show, submission))
      {:error, changeset} ->
        render(conn, "edit.html", submission: submission, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    submission = Repo.get!(Submission, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(submission)

    conn
    |> put_flash(:info, "Submission deleted successfully.")
    |> redirect(to: submission_path(conn, :index))
  end

  def draw_winner(conn, _params) do
    subs = Repo.all(from subs in Submission, where: subs.winner == false)
    double_subs = Repo.all(from dbl_subs in DoubleSubmission, where: dbl_subs.winner == false)
    submissions = Enum.concat(subs, double_subs)
    if Enum.empty?(submissions) do
      conn
      |> put_flash(:info, "No eligible winners :(")
      |> redirect(to: submission_path(conn, :index))
    else
      winning_submission = Enum.random(submissions)

      Submission.changeset(winning_submission, %{winner: true})
      |> Repo.update

      DoubleSubmission.changeset(winning_submission, %{winner: true})
      |> Repo.update

      ExTwitter.update("Congrats @#{winning_submission.twitter_handle}! You are a raffle winner! #dsmwebgeekfest")

      conn
      |> put_flash(:info, "Winner was: #{winning_submission.first_name} #{winning_submission.last_name} - #{winning_submission.twitter_handle}")
      |> redirect(to: submission_path(conn, :index))
    end
  end
end

web/views/submission_view.ex
defmodule WebgeeksRaffle.SubmissionView do
  use WebgeeksRaffle.Web, :view
end

web/templates/submission/edit.html.eex
<h2>Edit submission</h2>

<%= form_for @changeset, submission_path(@conn, :update, @submission), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= text_input f, :first_name, class: "form-control", placeholder: "First name" %>
          <%= error_tag f, :first_name %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          <%= text_input f, :last_name, class: "form-control", placeholder: "Last name" %>
          <%= error_tag f, :last_name %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= text_input f, :job_title, class: "form-control", placeholder: "Job title" %>
      <%= error_tag f, :job_title %>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <%= text_input f, :twitter_handle, class: "form-control", placeholder: "Twitter" %>
          </div>
          <%= error_tag f, :twitter_handle %>
        </div>
        <div class="col-lg-6">
          <%= text_input f, :email, class: "form-control", placeholder: "Email adress" %>
          <%= error_tag f, :email %>
        </div>
    </div>
  </div>

  <div class="form-group">
    <%= checkbox f, :winner %>
    <%= label f, "Winner?" %>
    <%= error_tag f, :winner %>
  </div>

  <div class="col-lg-12">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/submission/index.html.eex
<div class="row">
  <div class="form-group">
    <%= link("Determine Winner", to: submission_path(@conn, :draw_winner), class: "btn btn-primary") %>
    <%= link "New submission", to: submission_path(@conn, :new), class: "btn btn-primary" %>
    <%= link "Double submissions", to: double_submission_path(@conn, :index), class: "btn btn-primary" %>
  </div>
</div>

<h2>Door Prize Entries</h2>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Job title</th>
      <th>Twitter handle</th>
      <th>Email</th>
      <th>Winner</th>

      <th>Actions</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for submission <- @submissions do %>
    <tr>
      <td><%= submission.first_name %></td>
      <td><%= submission.last_name %></td>
      <td><%= submission.job_title %></td>
      <td><%= submission.twitter_handle %></td>
      <td><%= submission.email %></td>
      <td><%= submission.winner %></td>

      <td class="text-right">
        <%= link "Edit", to: submission_path(@conn, :edit, submission), class: "btn btn-default btn-xs" %>
      </td>
      <td>
        <%= link "Delete", to: submission_path(@conn, :delete, submission), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/submission/new.html.eex
<h2>New submission</h2>

<%= form_for @changeset, submission_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= text_input f, :first_name, class: "form-control", placeholder: "First name" %>
          <%= error_tag f, :first_name %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          <%= text_input f, :last_name, class: "form-control", placeholder: "Last name" %>
          <%= error_tag f, :last_name %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= text_input f, :job_title, class: "form-control", placeholder: "Job title" %>
      <%= error_tag f, :job_title %>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <%= text_input f, :twitter_handle, class: "form-control", placeholder: "Twitter" %>
          </div>
          <%= error_tag f, :twitter_handle %>
        </div>
        <div class="col-lg-6">
          <%= text_input f, :email, class: "form-control", placeholder: "Email adress" %>
          <%= error_tag f, :email %>
        </div>
    </div>
  </div>

  <div class="col-lg-12">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/submission/show.html.eex
<h2>Submission for <%= "#{@submission.first_name} #{@submission.last_name}" %></h2>

<ul>

  <li>
    <strong>First name:</strong>
    <%= @submission.first_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @submission.last_name %>
  </li>

  <li>
    <strong>Job title:</strong>
    <%= @submission.job_title %>
  </li>

  <li>
    <strong>Twitter handle:</strong>
    <%= @submission.twitter_handle %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @submission.email %>
  </li>

</ul>
<div class="col-lg-12">
  <div class="row">
    <div class="form-group">
      <%= link "Edit", to: submission_path(@conn, :edit, @submission), class: "btn btn-primary" %>
      <%= link "View All", to: submission_path(@conn, :index), class: "btn btn-primary" %>
    </div>
  </div>
</div>